name: Test model

on:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  test-inference:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Clone the repository checkpoints
      run: |
        git init temp_repo
        cd temp_repo
        git remote add origin https://huggingface.co/LautaroOcho/Argentinian-audio-transcriptions
        git fetch origin
        git checkout origin/main -- checkpoints
        mv checkpoints ../
        cd ..
        rm -rf temp_repo

    - name: Run tests
      run: pytest tests/
