name: Test model

on:
  push:
    branches: [master, transformer]
  pull_request:
    branches: [master, transformer]

jobs:
  test-inference:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Clone the repository checkpoints
      run: |
        mkdir temp_repo
        cd temp_repo
        # Determinar la rama remota a usar (main o transformer)
        if [[ "${GITHUB_REF_NAME}" == "master" ]]; then
          BRANCH="main"
        else
          BRANCH="${GITHUB_REF_NAME}"
        fi
        echo "Cloning branch $BRANCH from Hugging Face repo"
        git clone --branch $BRANCH https://huggingface.co/LautaroOcho/Argentinian-audio-transcriptions .
        mv checkpoints ../
        cd ..
        rm -rf temp_repo

    - name: Run tests
      run: pytest .github/tests
